### ISSUE TITLE
Closing Socket Exception

### ISSUE THREAD

**Issue by dtg3** [iTrace-Dev/iTrace-Eclipse#33]
When disconnecting the plugin from the Core, a Socket Exception is throw. This prevents 
additional data from being record in plugin output XML. Output XML files get created, but contain not gaze data.
Example output:
``` xml
<?xml version="1.0" encoding="utf-8"?>
<itrace_plugin session_id="636940461947160449">
<environment screen_width="1536" screen_height="864" plugin_type="eclipse"/>
<gazes>
</gazes>
</itrace_plugin>
```

Stack Trace for Exception:
```
java.net.SocketException: Socket closed
	at java.base/java.net.SocketInputStream.socketRead0(Native Method)
	at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:185)
	at java.base/java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:326)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:392)
	at edu.ysu.itrace.ConnectionManager$1.run(ConnectionManager.java:64)
```

**Comment by dtg3** [comment]
Basic testing does not result in socket exception after disconnect.
